sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby
  - rbx
before_install:
  - gem update --system # Need for Ruby 2.5.0. https://github.com/travis-ci/travis-ci/issues/8978
  - gem install bundler
matrix:
  allow_failures:
    # Rubinius and JRuby have a lot of trouble and no large following, so I'm going to
    # allow failures on it until it gets more stable on Travis / Real Life(tm).
    # Let me know if you need it. Patches are welcome!
    - rvm: jruby
    - rvm: rbx
  fast_finish: true
cache: bundler
script: "rake"
